-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Firestorm.Object.Thread exposing (id, insertedAt, posts, title, updatedAt)

import Firestorm.InputObject
import Firestorm.Interface
import Firestorm.Object
import Firestorm.Scalar
import Firestorm.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Firestorm.Scalar.Id Firestorm.Object.Thread
id =
    Object.selectionForField "id" [] (Object.scalarDecoder |> Decode.map Firestorm.Scalar.Id)


insertedAt : SelectionSet Firestorm.Scalar.DateTime Firestorm.Object.Thread
insertedAt =
    Object.selectionForField "insertedAt" [] (Object.scalarDecoder |> Decode.map Firestorm.Scalar.DateTime)


posts : SelectionSet decodesTo Firestorm.Object.Post -> SelectionSet (List decodesTo) Firestorm.Object.Thread
posts object_ =
    Object.selectionForCompositeField "posts" [] object_ (identity >> Decode.list)


title : SelectionSet String Firestorm.Object.Thread
title =
    Object.selectionForField "title" [] Decode.string


updatedAt : SelectionSet Firestorm.Scalar.DateTime Firestorm.Object.Thread
updatedAt =
    Object.selectionForField "updatedAt" [] (Object.scalarDecoder |> Decode.map Firestorm.Scalar.DateTime)
