-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Firestorm.Object.User exposing (avatarUrl, id, insertedAt, name, updatedAt, username)

import Firestorm.InputObject
import Firestorm.Interface
import Firestorm.Object
import Firestorm.Scalar
import Firestorm.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


avatarUrl : SelectionSet String Firestorm.Object.User
avatarUrl =
    Object.selectionForField "avatarUrl" [] Decode.string


id : SelectionSet Firestorm.Scalar.Id Firestorm.Object.User
id =
    Object.selectionForField "id" [] (Object.scalarDecoder |> Decode.map Firestorm.Scalar.Id)


insertedAt : SelectionSet Firestorm.Scalar.DateTime Firestorm.Object.User
insertedAt =
    Object.selectionForField "insertedAt" [] (Object.scalarDecoder |> Decode.map Firestorm.Scalar.DateTime)


name : SelectionSet String Firestorm.Object.User
name =
    Object.selectionForField "name" [] Decode.string


updatedAt : SelectionSet Firestorm.Scalar.DateTime Firestorm.Object.User
updatedAt =
    Object.selectionForField "updatedAt" [] (Object.scalarDecoder |> Decode.map Firestorm.Scalar.DateTime)


username : SelectionSet String Firestorm.Object.User
username =
    Object.selectionForField "username" [] Decode.string
