-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Firestorm.Object exposing (Category(..), PaginatedCategories(..), Post(..), Thread(..), User(..))


type Category
    = Category


type PaginatedCategories
    = PaginatedCategories


type Post
    = Post


type Thread
    = Thread


type User
    = User
